package com.last.study.enums;

public enum UserRegisterResult {
    USER_REGISTER_RESULT_FAILURE,
    USER_REGISTER_RESULT_FAILURE_EMAIL_DUPLICATED,
    USER_REGISTER_RESULT_FAILURE_NICKNAME_DUPLICATED,
    USER_REGISTER_RESULT_FAILURE_CONTACT_DUPLICATED,
    USER_REGISTER_RESULT_SUCCESS,
    USER_REGISTER_RESULT_PASSWORD_NOT_MATCHED
}
